### ISSUE TITLE
How can I adjust the colors of a Format-SpectrePanel command, or a Format-SpectreTable command?

### ISSUE THREAD

**Issue by fmotion1** [ShaunLawrie/PwshSpectreConsole#10]
https://pwshspectreconsole.com/reference/formatting/format-spectretable/
https://pwshspectreconsole.com/reference/formatting/format-spectrepanel/

Neither show examples on how to customize colors for these elements. Am I missing something?

**Comment by trackd** [comment]
Both commands have a `-Color` parameter (in the docs)

```ps1
Format-SpectrePanel -Data 'testing 123, testing' -Title 'no 1' -Border Heavy -Color Teal
```
theres autocompletion for all available colors as well.
to get a list
```ps1
([Spectre.Console.Color] | Get-Member -Static -Type Properties).Name
```
