### ISSUE TITLE
Is there any possible way we can enable colored text when typing a response after invoking Read-SpectreText?

### ISSUE THREAD

**Issue by fmotion1** [ShaunLawrie/PwshSpectreConsole#17]
`Read-SpectreText -Question "[#b1b6bb]Please type the name of the package(s) you want to install gloablly separated by spaces:[/]"`

It would be really cool to do this:

Before:

![before](https://github.com/ShaunLawrie/PwshSpectreConsole/assets/33441569/dbd1c52f-5947-4dd3-98a7-b1eff3273cd2)

After:

![after](https://github.com/ShaunLawrie/PwshSpectreConsole/assets/33441569/f74de27c-b4cb-4d34-870e-3ec6738d7706)

Would this be possible? I'm going to look into it as well, but if you already have an easy way to implement it, that would be great.

**Comment by ShaunLawrie** [comment]
Try -AnswerColor on prerelease atm, I pushed a bunch of tests and tried to add this too https://github.com/ShaunLawrie/PwshSpectreConsole/commit/db2c0580b9769150e2a28b30944203cbcc1554ab#diff-fcd2ab94bf0b8c672681187e136d9fd2936f3a8712002213965b57e1e7b0ae20R34

**Comment by fmotion1** [comment]
Gonna give all the new changes a whirl now!

**Comment by ShaunLawrie** [comment]
This should be working, raise the issue again if it doesn't do what you were wanting :)
