### ISSUE TITLE
[Implimented Feature, PR #23] New -HeaderColor parameter for Format-SpectreTable. 

### ISSUE THREAD

**Issue by fmotion1** [ShaunLawrie/PwshSpectreConsole#25]
### [Link to PR#23](https://github.com/ShaunLawrie/PwshSpectreConsole/pull/23)

1. Refactored [Add-TableColumns](https://github.com/ShaunLawrie/PwshSpectreConsole/pull/23/commits/c913f9b1e131e86359a772547f59419198faceee#diff-d70d9f4f90ec13080be657c7421462cce59adf852f1d40a868bfe91aad033c01) to support a new table header color parameter.
2. Added and modified [Format-SpectreTable](https://github.com/ShaunLawrie/PwshSpectreConsole/pull/23/commits/c913f9b1e131e86359a772547f59419198faceee#diff-413b430460d887746aa3df62be091c7dc06b4d4ae8226db30e31ad3724b92d6f) to support the new table header color parameter.

### Example Usage
---

```powershell
$Obj1 = [PSCustomObject]@{
    Name = "Explorer"
    Path = "C:\Windows"
    Category = "System"
}

$Obj2 = [PSCustomObject]@{
    Name = "Steam"
    Path = "C:\Program Files\Steam"
    Category = "Gaming"
}

$Obj3 = [PSCustomObject]@{
    Name = "Direct Folders"
    Path = "C:\Program Files (x86)\Direct Folders"
    Category = "Productivity"
}

$Obj4 = [PSCustomObject]@{
    Name = "Discord"
    Path = "C:\Program Files\Discord"
    Category = "Communication"
}

$List = [System.Collections.Generic.List[Object]]@()
$List.Add($Obj1) | Out-Null
$List.Add($Obj2) | Out-Null
$List.Add($Obj3) | Out-Null
$List.Add($Obj4) | Out-Null

Format-SpectreTable -Data $List -Border Square -Color "#585858" -HeaderColor "#b6bfff"

# Alternatively:

$List | Format-SpectreTable -Border Square -Color "#585858" -HeaderColor "#b6bfff"
```

### Output:
---
![Code_stEE84HwwV](https://github.com/ShaunLawrie/PwshSpectreConsole/assets/33441569/e80f8830-209c-4f43-90d3-758910602266)

### Future Plans:
---

I'd like to implement a `-TextColor` parameter, and a `-TitleColor` parameter as well. Their functionality should be self evident.

Also if/when this occurs I think changing `-Color` to `-TableBorderColor` would probably be appropriate.

Any comments or critiques welcome.

**Comment by ShaunLawrie** [comment]
Implemented in https://github.com/ShaunLawrie/PwshSpectreConsole/releases/tag/v1.7.0
I used the comments on the PR https://github.com/ShaunLawrie/PwshSpectreConsole/pull/23 to recreate it because your prerelease branch was force pushed and lost the original commits
