### ISSUE TITLE
Update Row/Col Data in SpectreTable

### ISSUE THREAD

**Issue by dfinke** [ShaunLawrie/PwshSpectreConsole#47]
I see in the demo using Format-SpectreTable and Invoke-SpectreLive you can add data to a table with Add-SpectreTableRow.

Is there a way to update data in a row and column?

**Comment by ShaunLawrie** [comment]
You can but not via a powershell cmdlet yet.

You can access it directly from the spectre console extension method like
this:

[Spectre.Console.TableExtensions]::UpdateCell($table, $rowIndex,
$columnIndex, “new value”) > $null

The method signature inside spectre expects that new value to be one of two
types:
A string so you’ll need to ToString() whatever you put in there.
Or a renderable item for new value like the variable $newValue from
‘$newValue = Write-SpectreHost “[red]hello[/]” -PassThru’

**Comment by ShaunLawrie** [comment]
![image](https://github.com/user-attachments/assets/aebda23e-2bb9-49f4-aa0d-7a315f9a0e18)

or with renderables

![image](https://github.com/user-attachments/assets/d6cf6f6b-311f-4848-8ed9-46335f89c678)

**Comment by dfinke** [comment]
Great, thanks for the clues. Time to dig a little deeper on spectre ext iteself.

**Comment by dfinke** [comment]
![UpdateCell](https://github.com/user-attachments/assets/0f2d96c6-7fcc-41eb-b70d-f1006a088db9)
