### ISSUE TITLE
Recommend defining CompatiblePSEditions

### ISSUE THREAD

**Issue by jdhitsolutions** [ShaunLawrie/PwshSpectreConsole#48]
The module manifest has a PowerShell requirement. If this is true, I would also recommend setting `CompatiblePSEditions = 'Core'"` in the manifest. I know that's the first place I look when checking for compatibility. The module name should be a good indication, but it never hurts to be thorough.

**Comment by ShaunLawrie** [comment]
Thanks for the recommendation Jeff. That psd1 format has so many options.
It means a lot to know you've taken a peek at my code, thanks for all the work you do in the powershell space (and for all the QotD content in my twitter feed 😆)
