### ISSUE TITLE
Function or parameter in cmdlets to escape markup

### ISSUE THREAD

**Issue by ruckii** [ShaunLawrie/PwshSpectreConsole#5]
According to [Spectre.Console Best Practices](https://spectreconsole.net/best-practices):

> Do escape data when outputting any user input or any external data via Markup using the [EscapeMarkup](https://spectreconsole.net/api/Spectre.Console/Markup/e35ae760) method on the data. Any user input containing [ or ] will likely cause a runtime error while rendering otherwise.

There are at least 2 options:
- Parameter in each cmdlet:
```
function Format-SpectrePanel {
    param (
        [Parameter(ValueFromPipeline)]
        [string] $Data,
        [string] $Title,
        [string] $Border = "Rounded",
        [switch] $Expand,
        [switch] $EscapeMarkup,
        [ValidateSpectreColor()]
        [ArgumentCompletionsSpectreColors()]
        [string] $Color = $script:AccentColor.ToString()
    )
    if($EscapeMarkup) {
        $Data = [Spectre.Console.Markup]::Escape($Data)
    }
```
- Use Spectre.Console method to escape data before PwshSpectreConsole cmdlet call:
```
#Requires -Version 7.0
#Requires -Modules PwshSpectreConsole

$data = "][[][]]][[][][]["
$escapedData = [Spectre.Console.Markup]::Escape($data)
Format-SpectrePanel -Title "Escaped data" -Data $escapedData
Format-SpectrePanel -Title "Unescaped data" -Data $data # Exception
```

**Comment by ShaunLawrie** [comment]
I added a function for escaping `Get-SpectreEscapedText`. I wonder if that's enough for most cases? It just pipes the text through that escape function you have there so you can use it in a pipeline.

Cases like your one above:  
![image](https://github.com/ShaunLawrie/PwshSpectreConsole/assets/13159458/4258b602-e263-4144-aaa8-15c6839e2a72)

And receiving untrusted input like the best practice doc talks about:  
![image](https://github.com/ShaunLawrie/PwshSpectreConsole/assets/13159458/8fdb4be7-f0b9-41ec-80fc-bd4344b74c77)

And mixtures of escaped and unescaped data:  
![image](https://github.com/ShaunLawrie/PwshSpectreConsole/assets/13159458/81fb36f3-0c50-49a6-a294-3eb19b20ed7f)

I've pushed this and your other PR to psgallery in https://github.com/ShaunLawrie/PwshSpectreConsole/releases/tag/v0.2.3
Thanks for the feedback.

**Comment by ruckii** [comment]
Escaping function is what was needed! Thanks a lot!
