### ISSUE TITLE
 Possible feature request - Group Select a single object "Read-SpectreSelectionGrouped" and/or Format-SpectreTree with single selection and no select all

### ISSUE THREAD

**Issue by kkerr2005** [ShaunLawrie/PwshSpectreConsole#53]
Having lots of fun with this module , thank you so much for putting the time in to create something so awesome! I find this really useful for getting code out the door quickly to my users. :)

I'm just wondering if its possible to have a grouped selection of a single item rather than multiple or perhaps a tree view where I can select a single item?

Thanks

**Comment by kkerr2005** [comment]
That looks perfect, love a bit of hackery, thanks for the thanks for the thanks Shaun

🤣

**Comment by ShaunLawrie** [comment]
This is in the prerelease version at the moment. I have a bunch of work to do before it will hit main but in the meantime you can try it out with `Update-Module PwshSpectreConsole -AllowPrerelease` https://prerelease.pwshspectreconsole.com/reference/prompts/read-spectreselectiongrouped/
