### ISSUE TITLE
Format-SpectreTable Breaks if a custom border is specified.

### ISSUE THREAD

**Issue by fmotion1** [ShaunLawrie/PwshSpectreConsole#9]
I've tried `Format-SpectreTable -Data $data -Border "1"`
And `Format-SpectreTable -Data $data -Border 1`

Both formats give me:

```Line |
 950 |          [Spectre.Console.AnsiConsole]::Write($table)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Write" with "1" argument(s): "Object reference not set to an      
     | instance of an object."
```

Full Code:

```
$data = @(
    [pscustomobject]@{Name="John"; Age=25; City="New York"},
    [pscustomobject]@{Name="Jane"; Age=30; City="Los Angeles"}
)
Format-SpectreTable -Data $data -Border "1"
Format-SpectreTable -Data $data -Border 1
```

Just a FYI and maybe something to look into.

**Comment by trackd** [comment]
you can see the valid options like this,
```ps1
([Spectre.Console.TableBorder] | Get-Member -Static -Type Properties).Name
```

would probably be a bit easier to handle them like colors are in `Attributes.psm1`
ie by adding `ValidateSpectreTableBorder` & `ArgumentCompletionsSpectreTable`

**Comment by trackd** [comment]
I added a few more completion and validationsclasses locally, gonna look over the other functions as well and ill try and push it later tonight.
If theres interest that is.
